### ISSUE TITLE
php-fpm stall issue

### ISSUE THREAD

**Issue by Xon** [iuscommunity-pkg/php70u#1]
http://forum.remirepo.net/viewtopic.php?pid=8375

It looks like Huge Page usage can cause random stalls in CentOS 6.

(Not sure if php-fpm will be in the base php70u package or it's own)

**Comment by carlwgeorge** [comment]
Howdy @Xon,

Thanks for bringing this up.  I'd already noticed the corresponding upstream bug reports.  The fix is already in the master branch; I'll attempt to include it as a patch.  Luckily we won't have to carry the patch for long, as the fix is planned to be included in the 7.0.1 release.

**Comment by carlwgeorge** [comment]
Oh yes, and to clarify, fpm is part of the main PHP codebase, so it is included as a subpackage of the main PHP package.

**Comment by Xon** [comment]
Cheers, great to hear.

**Comment by carlwgeorge** [comment]
After talking with @remicollet about this, it appears the [upstream commit](http://git.php.net/?p=php-src.git;a=patch;h=e9a8d7ff1d59cbcaf4b5cec728a94fb0d54dd993) I intended to use for my patch isn't a complete fix.  It may be better to just wait for 7.0.1.

**Comment by carlwgeorge** [comment]
7.0.1 released upstream, applied to our spec via 665ddd6.
