### ISSUE TITLE
Please use "15" for httpd module configuration

### ISSUE THREAD

**Issue by remicollet** [iuscommunity-pkg/php70u#2]
```
-install -D -m 644 %{SOURCE9} $RPM_BUILD_ROOT%{_httpd_modconfdir}/10-php.conf
+install -D -m 644 %{SOURCE9} $RPM_BUILD_ROOT%{_httpd_modconfdir}/15-php.conf
```

This ensure it will be load after "php 5" possible configuration file (which can be provided by some RHSCL packages)

Also need to check 

```
 <IfModule !mod_php5.c>
```

Even if apache allow / try to load both, it will segfault (same symbols in both modules)

**Comment by remicollet** [comment]
Perhaps you should look first at my spec file, which is ready, and will be used for Fedora. Reinventing the wheel... (#remirepo is fedora's upstream)

**Comment by carlwgeorge** [comment]
Howdy @remicollet,

Thanks for your feedback.

While SCL-compatibility is not a goal of ours, we aren't necessarily opposed to this suggestion.  Are these changes going to be made to the Fedora spec file as well?  If so, we'll include them also.

> Perhaps you should look first at my spec file, which is ready, and will be used for Fedora. Reinventing the wheel... (#remirepo is fedora's upstream)

I am using your php70 spec file as a point of reference (as well as our php56u spec file) as I develop our php70u spec file.  I don't feel like it is reinventing the wheel per say.  Not everything in your spec file is going to be put into ours, and our spec file will have things yours doesn't.  You certainly have a deeper knowledge of PHP itself than we do, so we often defer to your expertise, even though we disagree on other packaging details.

**Comment by remicollet** [comment]
>  Are these changes going to be made to the Fedora spec file as well?

Yes, as I said #remirepo is fedora's upstream, so the php 7 spec file will be mine (after cleanup of conditional stuff, only needed for backports)

**Comment by remicollet** [comment]
> so we often defer to your expertise,

:)

Please understand that my main goal, as upstream, is the image of the "PHP Project" and adoption of newer versions. And whatever "repo" is used I prefer to see working packages, and so, the reason why I also try to give you such information.

**Comment by carlwgeorge** [comment]
I checked two different SCLs and they both put the config file in `/opt`, with very different names.
- php55

```
/opt/rh/httpd24/root/etc/httpd/conf.d/php55-php.conf
/opt/rh/httpd24/root/etc/httpd/conf.modules.d/10-php55-php.conf
```
- rh-php56

```
/opt/rh/httpd24/root/etc/httpd/conf.d/rh-php56-php.conf
/opt/rh/httpd24/root/etc/httpd/conf.modules.d/10-rh-php56-php.conf
```

Other observations:
- Based on the paths above, it appears that SCL php (mod_php) requires SCL httpd, so it is even further separated from possible conflicts.
- Stock EL7 uses the location `/etc/httpd/conf.modules.d/10-php.conf`, and SCLs are fully parallel with stock, so SCLs should never use that filename.  In other words, if SCL php is parallel with stock, then it is parallel with IUS.

I'm struggling to come up with a scenario where there could be a conflict.  Please help me understand.

**Comment by remicollet** [comment]
php54 SCL is build with system httpd

```
  /etc/httpd/conf.modules.d/10-php54-php.conf
```

**Comment by remicollet** [comment]
Closing as no value for IUS.
