### ISSUE TITLE
php70u-common doesn't provide zip extension

### ISSUE THREAD

**Issue by Xon** [iuscommunity-pkg/php70u#3]
The zip extension doesn't look to be included in php70u-common, which is I found unexpected as it is provided in the previous versions ie php55u-common and php56u-common.

**Comment by carlwgeorge** [comment]
Howdy @Xon, thanks for reaching out.

Our spec file is based on the Fedora spec file.  They disabled the bundled zip extension [a while back](http://pkgs.fedoraproject.org/cgit/php.git/commit/?id=591f19198771624a47e6837812f0af0194206a32).  I can see that we explicitly [re-enabled](https://github.com/iuscommunity-pkg/php55u/commit/dca23980c8b1a2951da271bff2e01dbffea3eaa9) it in `php55u`.  `php56u` appears to have always had it enabled.

In Fedora, `php-zip` is provided by `php-pecl-zip`.  It looks like our options are to either re-enable the bundled zip extension, or build (and maintain) a `php70u-pecl-zip` package.  In general we like to align with Fedora when possible.  Let me do some research to see if there was a reason for avoiding a pecl zip package in the past.

**Comment by Xon** [comment]
:+1:

**Comment by carlwgeorge** [comment]
I can't find much information on this.  We are going to follow Fedora's lead on this and leave it out of the php70u package and ship it separately as php70u-pecl-zip.  That will allow us to update it independently of the main package.  When you get the time open a [wishlist request](https://github.com/iuscommunity/wishlist/issues) and we will get started on it.

**Comment by carlwgeorge** [comment]
Per the discussion in iuscommunity/wishlist#32, we are going to re-introduce the zip extension to the common subpackage.
