### ISSUE TITLE
PHP 7 and json

### ISSUE THREAD

**Issue by iler** [iuscommunity-pkg/php70u#4]
As jsonc is now replaced with jsond in PHP 7 (https://wiki.php.net/rfc/jsond) I was wondering will jsond be offered to install as a pecl package like jsonc was in PHP 5.6?

**Comment by b-harper** [comment]
Hye @iler,

In php56u, we used the jsonc pecl modules instead of the default json module at the request of @remicollet.  Seeing now that default json module has a sane license, we are using it for php70u.  Are there features missing in the php70u-json package? 

-Ben

**Comment by iler** [comment]
Hi @b-harper,

I installed php70u and bunch of other packages from IUS testing and when installing composer I got this error:
The json extension is missing.
Install it or recompile php without --disable-json

The reason why I'm asking because there is no php70u-json package available in IUS testing repository and the lack of json is currently preventing me to test php70u fully.

-Ilari

**Comment by b-harper** [comment]
What mirror are you using?  We have php70u-json packages is both the stable and tesing repo.

```
# rpm -qa |grep php
php70u-common-7.0.2-1.ius.centos7.x86_64
php70u-json-7.0.2-1.ius.centos7.x86_64
php70u-cli-7.0.2-1.ius.centos7.x86_64

# php -i |grep json
/etc/php.d/20-json.ini,
json
json support => enabled
json version => 1.4.0
```

**Comment by iler** [comment]
Oh, now it went through and installed it. Seems that there was a glitch in the universe and maybe some dirt in the caches ;)

Thanks anyways!
-Ilari
