### ISSUE TITLE
mssing dependency: libwebp

### ISSUE THREAD

**Issue by wingsoul** [iuscommunity-pkg/php70u#7]
my distribution is CentOS 6.8
After i ran the following for adding IUS repository:
`yum -y update`
`yum -y install epel-release`
`wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm`
`wget https://centos6.iuscommunity.org/ius-release.rpm`
`rpm -Uvh ius-release*.rpm`
`yum -y update`

Then i tried to install php70u by:
`yum -y install php70u php70u-pdo php70u-mysqlnd php70u-opcache php70u-xml php70u-mcrypt php70u-gd php70u-devel php70u-mysql php70u-intl php70u-mbstring php70u-bcmath php70u-json php70u-iconv`

Therefore, i need to download third party rpm:
`wget ftp://195.220.108.108/linux/epel/6/x86_64/libwebp-0.4.3-3.el6.x86_64.rpm`
`rpm -Uvh libwebp-0.4.3-3.el6.x86_64.rpm`

Finally, problem solved. But can IUS repository add libwebp package?

Thank you

**Comment by carlwgeorge** [comment]
Howdy @wingsoul,

libwebp is available in the EPEL repository.  When I install php70u-gd, the dependency is correctly resolved.

```
# yum -d1 install php70u-gd

===================================================================================
 Package              Arch          Version                      Repository   Size
===================================================================================
Installing:
 php70u-gd            x86_64        7.0.8-1.ius.centos6          ius         161 k
Installing for dependencies:
 libwebp              x86_64        0.4.3-3.el6                  epel        210 k
 php70u-common        x86_64        7.0.8-1.ius.centos6          ius         1.1 M

Transaction Summary
===================================================================================
Install       3 Package(s)

Total download size: 1.4 M
Installed size: 9.4 M
Is this ok [y/N]: y

Installed:
  php70u-gd.x86_64 0:7.0.8-1.ius.centos6                                           

Dependency Installed:
  libwebp.x86_64 0:0.4.3-3.el6      php70u-common.x86_64 0:7.0.8-1.ius.centos6     
```

Have you added any exclusions to your epel.repo file?

**Comment by carlwgeorge** [comment]
Since this is not an actual bug, I'm going to close this out.  If you would like some more assistance with repo management, feel free to join one or more of the following freenode IRC channels.

`#iuscommunity`
`#epel`
`#centos`
